blank_issues_enabled: false
contact_links:
  - name: Imposter documentation
    url: https://docs.imposter.sh/
    about: Please check the documentation before opening an issue.
  - name: Getting started
    url: https://docs.imposter.sh/getting_started/
    about: If you are new to Imposter, please check the getting started guide.
