blank_issues_enabled: false
contact_links:
  - name: Imposter documentation
    url: https://docs.imposter.sh/
    about: Please check the documentation before opening an issue.
  - name: GitHub Discussions
    url: https://github.com/orgs/imposter-project/discussions
    about: For general discussion, ideas, and community Q&A.
